# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adatalab.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-130237912-1"

twitter_username:
github_username:

# Build settings
markdown: kramdown
